[window]
decorations = "None"

[general]
import = [
    "~/.config/alacritty/themes/noctalia.toml",
]

[font]
size=12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

