alias lg "lazygit"
alias cd "z"
alias n "nvim"
alias c "code"
alias nano "micro"
alias ls "eza -l"
alias la "eza -la"
alias gl "git log --oneline"
alias gc "git add .; and git commit -m"
alias qr "qrencode -t UTF8 -m 3"
alias uvinit "uv init --no-package"