-- AUTOGENERATED HYPRLAND CONFIG - Entry Point
-- https://wiki.hypr.land/Configuring/Start/

-- MY PROGRAMS
local terminal = "alacritty"
local fileManager = "nautilus"
local menu = "hyprlauncher"

-- Load modules
require("monitors").setup(hl)
require("autostart").setup(hl)
require("env").setup(hl)
require("appearance").setup(hl)
require("layouts").setup(hl)
require("input").setup(hl)
require("bindings").setup(hl, terminal, fileManager, menu)
require("window-rules").setup(hl)
require("misc").setup(hl)

-- Noctalia theme
require("noctalia").apply_theme()